package model;
// Generated Jun 24, 2014 1:14:59 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private Integer id;
     private Pedido pedido;
     private String nome;
     private String email;
     private Date dataNasc;
     private String telFixo;
     private String telCel;
     private String endereco;
     private Integer numero;
     private String bairro;
     private String cidade;
     private String uf;
     private String complemento;

    public Cliente() {
    }

	
    public Cliente(Pedido pedido) {
        this.pedido = pedido;
    }
    public Cliente(Pedido pedido, String nome, String email, Date dataNasc, String telFixo, String telCel, String endereco, Integer numero, String bairro, String cidade, String uf, String complemento) {
       this.pedido = pedido;
       this.nome = nome;
       this.email = email;
       this.dataNasc = dataNasc;
       this.telFixo = telFixo;
       this.telCel = telCel;
       this.endereco = endereco;
       this.numero = numero;
       this.bairro = bairro;
       this.cidade = cidade;
       this.uf = uf;
       this.complemento = complemento;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getDataNasc() {
        return this.dataNasc;
    }
    
    public void setDataNasc(Date dataNasc) {
        this.dataNasc = dataNasc;
    }
    public String getTelFixo() {
        return this.telFixo;
    }
    
    public void setTelFixo(String telFixo) {
        this.telFixo = telFixo;
    }
    public String getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }




}


