package model;
// Generated Jun 24, 2014 1:14:59 AM by Hibernate Tools 3.6.0



/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer id;
     private Pedido pedido;
     private String nome;

    public Funcionario() {
    }

	
    public Funcionario(Pedido pedido) {
        this.pedido = pedido;
    }
    public Funcionario(Pedido pedido, String nome) {
       this.pedido = pedido;
       this.nome = nome;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }




}


