package model;
// Generated Jun 24, 2014 1:14:59 AM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private String status;
     private Date data;
     private Set funcionarios = new HashSet(0);
     private Set produtos = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Pedido() {
    }

    public Pedido(String status, Date data, Set funcionarios, Set produtos, Set clientes) {
       this.status = status;
       this.data = data;
       this.funcionarios = funcionarios;
       this.produtos = produtos;
       this.clientes = clientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


