package model;
// Generated Jun 24, 2014 1:41:25 AM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Produto produto;
     private Cliente cliente;
     private Funcionario funcionario;
     private String status;
     private Date data;

    public Pedido() {
    }

	
    public Pedido(Produto produto, Cliente cliente, Funcionario funcionario) {
        this.produto = produto;
        this.cliente = cliente;
        this.funcionario = funcionario;
    }
    public Pedido(Produto produto, Cliente cliente, Funcionario funcionario, String status, Date data) {
       this.produto = produto;
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.status = status;
       this.data = data;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


