package model;
// Generated Jun 25, 2014 6:32:55 PM by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private Integer id;
     private Cliente cliente;
     private Funcionario funcionario;
     private String status;
     private Date data;
     private Float valor;
     private int produtoId;
     private Set produtos = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(Cliente cliente, Funcionario funcionario, int produtoId) {
        this.cliente = cliente;
        this.funcionario = funcionario;
        this.produtoId = produtoId;
    }
    public Pedido(Cliente cliente, Funcionario funcionario, String status, Date data, Float valor, int produtoId, Set produtos) {
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.status = status;
       this.data = data;
       this.valor = valor;
       this.produtoId = produtoId;
       this.produtos = produtos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


